"""Resume compiler implementation."""

from typing import Any

from ..base import LatexCompiler
from ..processors import get_processor_for_section


class ResumeCompiler(LatexCompiler):
    """Resume compiler for generating PDF resumes.

    This class handles the compilation of resume data into LaTeX format
    and then into PDF. It uses templates and placeholder substitution
    to generate the final document.
    """

    def __init__(self):
        """Initialize the resume compiler."""
        super().__init__()

    def _log_data_structure(self, section_name: str, data: Any, message: str):
        """Log information about the structure and type of data for debugging.

        Args:
            section_name: Name of the section being processed
            data: The data to log information about
            message: Additional message for context
        """
        if data is None:
            self.logger.debug(f"{section_name} {message} data is None")
            return

        if isinstance(data, str):
            self.logger.debug(
                f"{section_name} {message} is string, length: {len(data)}, starts with: {data[:50]}..."
            )
        elif isinstance(data, dict):
            self.logger.debug(
                f"{section_name} {message} is dict with keys: {list(data.keys())}"
            )
        elif isinstance(data, list):
            self.logger.debug(
                f"{section_name} {message} is list with {len(data)} items"
            )
            if data and isinstance(data[0], list):
                self.logger.debug(
                    f"{section_name} {message} appears to be nested arrays"
                )
        else:
            self.logger.debug(f"{section_name} {message} is {type(data).__name__}")

    async def generate_tex_content(
        self,
        resume_content: dict[str, Any],
        portfolio_data: dict[str, Any] | None = None,
        template: dict | None = None,
    ) -> str:
        """Generate the full LaTeX content for a resume.

        Args:
            resume_content: The structured resume content generated by the LLM.
            portfolio_data: The user's full portfolio data (optional but needed for career summary).
            template: The LaTeX template data (optional).

        Returns:
            The complete LaTeX document as a string.
        """
        self.logger.debug("Starting LaTeX content generation for resume")
        self._log_data_structure("initial resume_content", resume_content, "input")
        self._log_data_structure("initial portfolio_data", portfolio_data, "input")

        document_parts = []

        # Define the expected order of sections
        sections = [
            "personal_information",
            "career_summary",
            "skills",
            "work_experience",
            "education",
            "projects",
            "awards",
            "publications",
            "certifications",  # Assuming certifications might be included
        ]

        # Filter sections based on what's actually present in the resume_content
        sections = [s for s in sections if s in resume_content]
        self.logger.debug(f"Processing sections in order: {sections}")

        # Process each section
        for section_name in sections:
            # Get section data directly from the input dictionary (LLM output)
            section_data = resume_content.get(section_name)

            # Skip if no data
            if not section_data:
                self.logger.debug(f"No data for section {section_name}, skipping")
                continue

            # Ensure section_data is a dictionary for modification
            if not isinstance(section_data, dict):
                self.logger.warning(
                    f"Section data for '{section_name}' is not a dict ({type(section_data)}), skipping augmentation."
                )
            else:
                # <<< START MODIFICATION FOR CAREER SUMMARY >>>
                if section_name == "career_summary":
                    if portfolio_data and "career_summary" in portfolio_data:
                        portfolio_summary = portfolio_data["career_summary"]
                        if (
                            isinstance(portfolio_summary, dict)
                            and "years_of_experience" in portfolio_summary
                        ):
                            years_exp = portfolio_summary["years_of_experience"]
                            # Add years_of_experience from portfolio to the LLM data
                            section_data["years_of_experience"] = years_exp
                            self.logger.info(
                                f"Added years_of_experience ({years_exp}) to career_summary data."
                            )
                        else:
                            self.logger.warning(
                                "Could not find 'years_of_experience' in portfolio career_summary."
                            )
                    else:
                        self.logger.warning(
                            "Portfolio data or portfolio career_summary missing, cannot add years_of_experience."
                        )
                # <<< END MODIFICATION FOR CAREER SUMMARY >>>

            try:
                # Get the processor for this section
                section_processor = get_processor_for_section(section_name)()

                # Process the section content - now career_summary has years_of_experience
                processed_content = section_processor.process(section_data)

                # Log processed content
                self._log_data_structure(
                    section_name, processed_content, "after processing"
                )

                # Skip empty sections
                if not processed_content:
                    self.logger.debug(
                        f"Section {section_name} produced empty content, skipping"
                    )
                    continue

                # Add the processed content directly to the document parts
                document_parts.append(processed_content)
                self.logger.debug(f"Added {section_name} section")

            except Exception as e:
                self.logger.error(f"Error processing {section_name}: {e}")
                self.logger.error(f"Section data: {str(section_data)[:100]}")

        if (
            not template
            or "header" not in template
            or "preamble" not in template["header"]
        ):
            raise ValueError(
                "Resume LaTeX generation requires template header preamble"
            )
        preamble = str(template["header"]["preamble"])

        # Format the complete document
        latex_content = preamble + "\n"
        latex_content += "\\begin{document}\n\n"
        latex_content += "".join(document_parts)
        latex_content += "\\end{document}"

        return latex_content
